services:
    web:
        build: ./backend
        ports:
            - "8000:80"
        volumes:
            - "./backend:/app:rw"
            - "./data:/data:rw"
        command: python manage.py runserver 0.0.0.0:80
        networks:
            - djangocmsnet
        env_file: .env-local

    frontend:
        build: ./frontend/quiz
        ports:
            - "5173:5173"
        volumes:
            - "./frontend/quiz:/app"
            - quiz_app_node_modules:/app/node_modules
        command: >
            sh -c "npm install --no-audit --no-fund &&
                   npm run dev"

        networks:
            - djangocmsnet

networks:
    djangocmsnet:

volumes:
    quiz_app_node_modules:
