# Generated by Django 5.2.3 on 2025-06-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuiz.category')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('min_score', models.FloatField()),
                ('questions', models.ManyToManyField(related_name='tests', to='appQuiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField()),
                ('score', models.FloatField(default=0)),
                ('IP', models.GenericIPAddressField()),
                ('duration', models.FloatField(help_text='Tempo in minuti')),
                ('revision_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appQuiz.sex')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuiz.test')),
            ],
        ),
    ]
