# Generated by Django 5.2.3 on 2025-06-25 07:40

from django.db import migrations
from djangocms_text.fields import HTMLField


class Migration(migrations.Migration):
    dependencies = [
        ("appQuiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=HTMLField(),
        ),
    ]
