# Generated by Django 5.2.3 on 2025-06-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuiz', '0002_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='appQuiz.question'),
        ),
    ]
