# Generated by Django 5.2.3 on 2025-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuiz', '0003_alter_answer_id_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correction',
            field=models.TextField(blank=True),
        ),
    ]
