# Generated by Django 5.2.3 on 2025-06-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuiz', '0004_answer_correction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuiz.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuiz.question')),
                ('test_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuiz.testexecution')),
            ],
        ),
    ]
