# Generated by Django 5.2.3 on 2025-07-06 08:51

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQuiz', '0006_givenanswer_answer_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='givenanswer',
            options={'verbose_name': 'Given Answer', 'verbose_name_plural': 'Given Answers'},
        ),
        migrations.AlterModelOptions(
            name='testexecution',
            options={'ordering': ['-execution_time']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='correction',
            field=djangocms_text.fields.HTMLField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=djangocms_text.fields.HTMLField(),
        ),
    ]
